// Header for ease-of-use only

#pragma once
#pragma comment(lib, "kernel32.lib")
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "winspool.lib")
#pragma comment(lib, "comdlg32.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "oleaut32.lib")
#pragma comment(lib, "uuid.lib")
#pragma comment(lib, "odbc32.lib")
#pragma comment(lib, "odbccp32.lib")
#pragma comment(lib, "OpenGL32.lib")
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "Iphlpapi.lib")
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "Secur32.lib")
#pragma comment(lib, "Bcrypt.lib")
#pragma comment(lib, "libcrypto.lib")
#pragma comment(lib, "libxml2.lib")
#pragma comment(lib, "charset.lib")
#pragma comment(lib, "iconv.lib")
#pragma comment(lib, "turbojpeg.lib")
#pragma comment(lib, "poly2tri.lib")
#pragma comment(lib, "Irrlicht.lib")
#pragma comment(lib, "minizip.lib")
#pragma comment(lib, "kubazip.lib")
#pragma comment(lib, "libssl.lib")
#pragma comment(lib, "jpeg.lib")
#pragma comment(lib, "glfw3.lib")
#pragma comment(lib, "libssl.lib")
#pragma comment(lib, "libssh2.lib")
#pragma comment(lib, "crypt32.lib")



#ifdef _DEBUG
#pragma comment(lib, "bz2d.lib")
#pragma comment(lib, "libcurl-d.lib")
#pragma comment(lib, "glew32d.lib")
#pragma comment(lib, "libprotobufd.lib")
#pragma comment(lib, "zlibd.lib")
#pragma comment(lib, "tiffd.lib")
#pragma comment(lib, "webpd.lib")
#pragma comment(lib, "IlmImf-2_5_d.lib")
#pragma comment(lib, "Iex-2_5_d.lib")
#pragma comment(lib, "IlmThread-2_5_d.lib")
#pragma comment(lib, "Imath-2_5_d.lib")
#pragma comment(lib, "Half-2_5_d.lib")
#pragma comment(lib, "lzmad.lib")
#pragma comment(lib, "libszip_D.lib")
#pragma comment(lib, "libhdf5_D.lib")
#pragma comment(lib, "lzmad.lib")
#pragma comment(lib, "lz4d.lib")
#pragma comment(lib, "libpng16d.lib")
#pragma comment(lib, "opencv_cored.lib")
#pragma comment(lib, "opencv_imgcodecsd.lib")
#pragma comment(lib, "opencv_imgprocd.lib")
#pragma comment(lib, "opencv_highguid.lib")
#pragma comment(lib, "opencv_hdfd.lib")
#else
#pragma comment(lib, "bz2.lib")
#pragma comment(lib, "libprotobuf.lib")
#pragma comment(lib, "libcurl.lib")
#pragma comment(lib, "glew32.lib")
#pragma comment(lib, "zlib.lib")
#pragma comment(lib, "tiff.lib")
#pragma comment(lib, "webp.lib")
#pragma comment(lib, "IlmImf-2_5.lib")
#pragma comment(lib, "IlmThread-2_5.lib")
#pragma comment(lib, "Imath-2_5.lib")
#pragma comment(lib, "Half-2_5.lib")
#pragma comment(lib, "Iex-2_5.lib")
#pragma comment(lib, "lzma.lib")
#pragma comment(lib, "lz4.lib")
#pragma comment(lib, "libpng16.lib")
#pragma comment(lib, "libszip.lib")
#pragma comment(lib, "libhdf5.lib")
#pragma comment(lib, "opencv_core.lib")
#pragma comment(lib, "opencv_imgcodecs.lib")
#pragma comment(lib, "opencv_imgproc.lib")
#pragma comment(lib, "opencv_highgui.lib")
#pragma comment(lib, "opencv_hdf.lib")
#endif


#include <GL/glew.h> // Necessary to define GLEW.h before windows header, else there's an error
#ifdef _WIN32
#include <Windows.h>
#else
// CROSS PLATFORM CODE HERE
#endif
